dist: xenial
# Enable C++ support
language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y g++-7
  - export CXX=/usr/bin/g++-7

script:
  - make
