notifications:
  email: false

os: linux
dist: xenial
# Enable C++ support
language: cpp
env:
  python: '3.6'
matrix:
  include:
    - env: COMPILER=clang++
      os: osx
      osx_image: xcode10.2

    - env: COMPILER=clang++-76
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6

    - env: COMPILER=g++-7
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test



before_install:
  - pip install numpy --user

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -xf clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LLVM_DIR=${TRAVIS_BUILD_DIR}/clang+llvm-8.0.0-x86_64-apple-darwin; fi

install:
  - export CXX=${COMPILER}

script:
  - $CXX --version
  - make && make test
