notifications:
  email: false

os: linux
dist: xenial
# Enable C++ support
language: cpp

matrix:
  include:

    - env: COMPILER=clang++
      os: osx
      osx_image: xcode8.1
      compiler: clang

    - env: COMPILER=clang++-7 
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: COMPILER=g++-7
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test



before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y g++-7
  #- export CXX=/usr/bin/g++-7

install:
  - export CXX=${COMPILER}
script:
  - make
