notifications:
  email: false

os: linux
dist: xenial
# Enable C++ support
language: cpp
env:
  python: '3.6.7'
matrix:
  include:
    - env: COMPILER=clang++-7
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: COMPILER=g++-7
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test



before_install:
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - python3 get-pip.py --user
  - pip3 install numpy --user

install:
  - export CXX=${COMPILER}

script:
  - echo $CXX
  - $CXX --version
  - make && make test
