notifications:
  email: false

os: linux
dist: xenial
# Enable C++ support
language: cpp
env:
  python: '3.6.7'
matrix:
  include:
    - env: COMPILER=clang++
      os: osx
      osx_image: xcode10.2

    - env: COMPILER=clang++-7
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7

    - env: COMPILER=g++-7
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test



before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 get-pip.py --user; fi

  - python3 -m pip3 install --upgrade pip3
  - pip3 install numpy --user

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -xf clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LLVM_DIR=${TRAVIS_BUILD_DIR}/clang+llvm-8.0.0-x86_64-apple-darwin; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=${TRAVIS_BUILD_DIR}/clang+llvm-8.0.0-x86_64-apple-darwin/bin/${COMPILER}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=${COMPILER}; fi

script:
  - echo $CXX
  - $CXX --version
  - make && make test
