matrix:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
      packages:
          - g++-7
    env:
      - MATRIX_EVAL="CXX=g++-7"

  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CXX=clang++-5.0"



before_install:
  - eval "${MATRIX_EVAL}"

  
# Enable C++ support
language: cpp

# Compiler selection

  
install:
  # Set the ${CXX} variable properly
  #- export CXX=${COMPILER}


  # Travis machines have 2 cores
  - JOBS=2

script:
  - make
